# Generated by Django 3.0.7 on 2020-06-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
