# Generated by Django 3.0.7 on 2020-06-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_ficha_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='description',
            new_name='descripcion',
        ),
    ]
