# Generated by Django 3.0.7 on 2020-06-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_auto_20200615_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
